version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:6.0
    container_name: student-system-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: student_website
    volumes:
      - mongodb_data:/data/db
    networks:
      - student-network

  # 后端应用
  backend:
    build: .
    container_name: student-system-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/student_website?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - student-network
    volumes:
      - ./server/uploads:/app/server/uploads

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: student-system-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - student-network

volumes:
  mongodb_data:

networks:
  student-network:
    driver: bridge