services:
  - type: web
    name: student-website
    env: node
    plan: free
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_VERSION
        value: 10.8.2
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false

      - key: NODE_ENV
        value: production
      - key: SKIP_PREFLIGHT_CHECK
        value: true